### ISSUE TITLE
 Frida for python - ctypes?

### ISSUE THREAD

**Issue by prnvjb** [poxyran/misc#1]
Hi,
Thanks for this amazing tool. I'm loading a lib.so (c++ compiled) file directly into python with ctypes. I want to analyze this .so file functionality within the python itself. The tutorials I found with frida are mostly for android. Any guidance to analyze these .so fies that loaded in python-ctypes with frida instead of java?
Thanks for the help!

**Comment by crackinglandia** [comment]
Hi there!, sorry for the delay :P I would recommend you to join the Frida IRC channel or the Telegram group (https://frida.re/contact/) in order to ask anything you want. Ole is very nice guy and is going to give you an answer for sure.
